export const SET_LOCATION = 'SET_LOCATION';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_WEATHER = 'SET_WEATHER';
export const SET_FORECAST = 'SET_FORECAST';
export const SET_PAST_WEATHER = 'SET_PAST_WEATHER';